services:

  events:
    image: node:21-alpine3.19
    container_name: events
    hostname: events
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - TZ=America/La_Paz
    command: >
      sh -c "npm run build && npm run start"
    ports:
      - "${PORT}:${PORT}"
    networks:
      - server-network

networks: 
  server-network:
    external: true